### ISSUE TITLE
cookie in public source code

### ISSUE THREAD

**Issue by rooterkyberian** [Dyr-El/AdventOfCode2022#1]
https://github.com/Dyr-El/AdventOfCode2022/blob/10359f2c324c912d3099ce236889aab19e989d07/local_settings.py#L7

sharing credential can end up badly, better save it in some local file (for example ~/.cache or ~/.config dirs)

**Comment by Dyr-El** [comment]
Yes that is bad practice although this session key is not very sensitive and with a shortish time span. It is moved to an environment variable now,
